import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/navbar/Navbar";
import MainModal from "./(components)/modal/MainModal";
import FilterModal from "./(components)/modal/FilterModal";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <Navbar />
                <MainModal />
                <FilterModal />
                <div className="px-24 py-6">{children}</div>
            </body>
        </html>
    );
}
